-- Role: vet

-- DROP ROLE vet;

CREATE ROLE vet LOGIN
  ENCRYPTED PASSWORD 'md51d6fd74ace029809a2092af542bcbea7'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
COMMENT ON ROLE vet IS 'vet
vet';